Feature/e2e
CSCfi/metadata-submitter-frontend pull request #108
Opened 2020-12-04 10:08 UTC by saulipurhonen

### Description

Basic e2e test that covers:
- Folder creation
- Form save
- XML upload
- Wizard navigation
- Folder publishing

To run, execute **npx cypress open**

### Related issues

Closes #10 

### Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update (this needs a follow up PR)

### Changes Made

- Installed Cypress and cypress-file-upload packages
- Tested frontend logic with backend connection

### Testing

- [x] Tests do not apply

2020-12-04 10:09 UTC, saulipurhonen commented
Note: There isn't much more to test in current state of the app. This merge can be used as base for e2e tests with Cypress.

Also, CI and GH Actions integration aren't in this PR. Should we try to get those running as well?

2020-12-06 17:10 UTC, blankdots commented
> Also, CI and GH Actions integration aren't in this PR. Should we try to get those running as well?

yes I think those should be done as well this could be introduced as part of this PR or another PR  (if that is the case please create an issue about what will be done)
https://github.com/cypress-io/github-action - seems to be the way to go ?

Note: the workflow will change following https://github.com/CSCfi/metadata-submitter/pull/158 and https://github.com/CSCfi/metadata-submitter/pull/151

as the user would need login, but a mock AAI is provided in the integration tests of those PRs.

2020-12-06 17:15 UTC, blankdots commented on cypress/integration/app.spec.js
> +    // Upload an xml file. Need to wait for save. TODO: Better logic for waiting until last save is done
please do an issue detailing this To Do.

2020-12-06 17:15 UTC, blankdots commented on CONTRIBUTING.md
> +We use Cypress for e2e testing.
```suggestion
We use [Cypress](https://www.cypress.io/) for e2e testing.
```

2020-12-06 17:16 UTC, blankdots requested changes
I am ok with leaving `This example ...` in the cypress files but I must recognise don't look very nice.

We would reference the source and where to find more information.

the only requests of change would be:
- to have a github action for this.
- mention in main `README.md` how to run the tests

2020-12-07 06:33 UTC, saulipurhonen commented
> I am ok with leaving `This example ...` in the cypress files but I must recognise don't look very nice.
> 
> We would reference the source and where to find more information.
> 
> the only requests of change would be:
> 
> * to have a github action for this.
> * mention in main `README.md` how to run the tests

I agree that example file doesn't look good.
I Removed the file and added e2e testing info to README.md

2020-12-08 09:50 UTC, csc-jm approved these changes
LGTM

2020-12-08 10:17 UTC, blankdots approved these changes

2020-12-08 10:17 UTC, merged