Feature/workflows node js update
CSCfi/metadata-submitter-frontend pull request #655
Opened 2022-02-03 08:54 UTC by saulipurhonen

### Description

Node.js versions from 16.11.0 and up use NPM v8 which is what we want to use in development.

### Related issues

Closes #654 

### Type of change

- [x] New feature (non-breaking change which adds functionality)

### Changes Made

- Use Node version 16 in code style, E2E, format, type check & unit test workflows

### Testing

- [x] Tests do not apply

2022-02-03 08:59 UTC, blankdots requested changes
https://github.com/CSCfi/metadata-submitter-frontend/blob/develop/Dockerfile-dev - update that as well ?

2022-02-03 09:55 UTC, blankdots approved these changes

2022-02-03 09:57 UTC, blankdots commented
maybe change it in readme as well ?

2022-02-03 10:03 UTC, blankdots reviewed
https://github.com/CSCfi/metadata-submitter-frontend/blob/develop/.github/workflows/e2etests.yml#L16 can also be removed now I assume

2022-02-03 10:54 UTC, blankdots approved these changes

2022-02-08 07:31 UTC, hannyle approved these changes

2022-02-09 04:38 UTC, merged